### ISSUE TITLE
$file_storage_path other than /tmp does not seem to work

### ISSUE THREAD

**Issue by rbrecheisen** [pgaertig/nginx-big-upload#16]
Hi,

First of all, thanks for the great work on this Nginx extension. It looks really promising. So far, I managed to get the example configuration running inside a Docker container. My files are nicely uploaded in chunks and reported back to the upload page where I can download them again. I changed the nginx.conf slightly to use an alias directive in the /tmp location instead of a root directive. Also, the alias is pointing to /tmp/ instead of /. This seems to work.

However, when I change the $file_storage_path and alias to something else, e.g., /home then I get the following weird Nginx errors:

webserver    | nginx: [alert] lua_code_cache is off; this will hurt performance in /usr/local/nginx/conf/nginx.conf:24
webserver    | 2016/08/05 10:17:24 [error] 8#0: *1 [lua] big-upload.lua:41: Failed to open file /home/88224118406027090, client: 192.168.99.1, server: , request: "POST /upload HTTP/1.1", host: "192.168.99.100", referrer: "http://192.168.99.100/"

webserver    | 192.168.99.1 - - [05/Aug/2016:10:17:24 +0000] "POST /upload HTTP/1.1" 500 5 "http://192.168.99.100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"
webserver    | 192.168.99.1 - - [05/Aug/2016:10:17:29 +0000] "\x1F\x8B\x08\x08H\xFC\x88W\x00\x03data.nii\x00\x9C\xBDy\xD8m\xDBU\xD69\xE6\x5C\xFDZ{\xEF\xEF\xFB\xCE9\xF7\x9C\xDB\xF7\xB9\x897\xC9MCB\xE0\x92\x10\x08\x84\x10 \x01\x02A\x90F\x1AC\x80\xD0\xB7\x16\x8F\x1A\x04\xA1xP\x14\x0C E\x1FD\xA0D\xA4\x8BF\x90\x18\x10\x8CE!" 400 173 "-" "-"

So, it looks like big-upload.lua suddenly can't find the /home/<sessionid> directory even though the /home directory exists in the Docker image.

Any idea what the cause of this might be? Is there are hard-coded dependency on the /tmp directory? In the end I'd like to use a shared Docker data volume container with a mounted directory like /mnt/shared/files. But this assumes that I can point $file_storage_path to that mounted directory.

I attached my nginx.conf to this issue. Thanks in advance for your time!

Ralph
[nginx-yoda.conf.zip](https://github.com/pgaertig/nginx-big-upload/files/403579/nginx-yoda.conf.zip)

**Comment by pgaertig** [comment]
Hi Ralph, my first thought is: access rights. Nginx user should have at least write and execute rights to your /home directory.

**Comment by rbrecheisen** [comment]
Hi Piotr,

Thanks for your quick reply. That was indeed the problem as I discovered
just a few minutes ago :) I'm completely unfamiliar with Lua so it took me
some time to figure out that io.open() returns additional error information
if you wrap it in a print() statement. That information indicated that it
was a permission problem. All directories in my Docker container are owned
by the root user (which is something I need to work on later, this seems to
be the default for Docker). When I added 'user root;' to the nginx.conf it
was solved.

Thanks again for your help! I really like the fact that Nginx handles most
of the resumable upload functionality. That keeps my Python backend free
from any heavy lifting :)

Ralph


---
Ralph Brecheisen, Ph.D.

Brain Innovation B.V. and University of Maastricht
Oxfordlaan 55, 6229 EV
Maastricht (Netherlands)
*E* *brecheisen@brainvoyager.com <brecheisen@brainvoyager.com>*
*T* +31 6 46 230 127
http://nl.linkedin.com/in/ralphbrecheisen

**Comment by pgaertig** [comment]
Glad you sorted out the problem. However I would advise to change home dir user or group to `www-data` (or whatever user was configured for nginx) and `chmod` it instead of granting nginx total control with root user.
There is no software without bugs so the risk is that any bug in nginx, lua, this extension or whatever may open access to whole image (think replacing nginx with some rough one). Even containerization doesn't shield your host server as the technology still matures in terms of security.

**Comment by rbrecheisen** [comment]
Hi Piotr,

Yes, you're absolutely right. I read about the possible security issues and
I will look into that deeper.
For now, I just wanted to get it working. One step at a time :)

Thanks again!

Ralph



---
Ralph Brecheisen, Ph.D.

Brain Innovation B.V. and University of Maastricht
Oxfordlaan 55, 6229 EV
Maastricht (Netherlands)
*E* *brecheisen@brainvoyager.com <brecheisen@brainvoyager.com>*
*T* +31 6 46 230 127
http://nl.linkedin.com/in/ralphbrecheisen
