### ISSUE TITLE
Hangs if used together with auth_request

### ISSUE THREAD

**Issue by norbert-yoimo** [pgaertig/nginx-big-upload#19]
I'm trying to use this module together with the [auth_request module](http://nginx.org/en/docs/http/ngx_http_auth_request_module.html), so I can authorize the uploads before they happen, instead of doing that on the final chunk, however, if I include an `auth_request` directive in my config, nginx just hangs, without performing a request. If I remove the `auth_request` directive, everything works perfectly. I'm wondering if you have any idea what could cause this?

My config:

```
worker_processes  1;
pid /tmp/nginx-upload.pid;

error_log  /dev/stderr;
daemon off;

events {
    worker_connections  10;
}

http {
    server {
        listen 9000;

        access_log /dev/stdout combined;
        error_log /dev/stderr;

        # Max size of chunks
        client_max_body_size 10m;



        location = /upload {
            auth_request /auth; # This is the line that messes it up, if I remove this, the upload succeeds
            lua_code_cache off;
            set $storage backend_file;
            set $bu_checksum on;

            set $file_storage_path /srv/http/uploads;
            set $backend_url /finish;
            set $package_path '../?.lua';
            content_by_lua_file ../big-upload.lua;
        }

        location = /auth {
            internal;
            proxy_pass http://127.0.0.1/uploadtokens/auth;
            proxy_pass_request_body off;
        }

        location = /finish {
            internal;
            proxy_pass http://127.0.0.1/finish;
        }
    }
}
```

I'm on `4fb4541` and I have used the build_nginx_with_docker.sh script to build nginx, the only change I made was adding the `  --with-http_auth_request_module` flag.

**Comment by pgaertig** [comment]
That is quite clever, haven't tried it yet. Do you see any errors logged or time-out after a while? Foremost I would try to add below to `/auth` location block: 

    proxy_method GET;
    proxy_set_header Content-Length "";

That should prevent eventual issues with back-end fooled by headers which may stall on connection expecting some content to arrive.

Another issue may be already consumed request socket. The lua upload module binds to raw nginx TCP socket to grab content without buffering and blocking. In such case I would switch to `access_by_lua_block` and [older `access_by_lua` description](https://github.com/openresty/lua-nginx-module#access_by_lua) contains the example replacement of `auth_request`.

Please share your results whichever works or not.

**Comment by norbert-yoimo** [comment]
It was the `content-length`, it works perfectly now, thanks a lot!

**Comment by Grimeton** [comment]
Hi,

I had a similar problem while using a fastcgi backend for auth requests. After fiddling around a bit, and reading this ticket I figured it out:
`
location /authrequest {
    internal;
    alias /srv/http/auth;

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_read_timeout 600;
        fastcgi_pass_request_body off;
        fastcgi_param  REQUEST_METHOD "GET";
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
    index index.php;
}
`
Setting the `fastcgi_param REQUEST_METHOD "GET"` finally fixed it for me. Maybe it helps someone that runs into a similar problem.

Cu
