### ISSUE TITLE
Error when trying to build docker with nginx 1.15.x

### ISSUE THREAD

**Issue by minchopm** [pgaertig/nginx-big-upload#25]
Makefile:8: recipe for target 'build' failed
The command '/bin/sh -c DOCKER=1 /tmp/build_nginx.sh &&     apt-get install dumb-init zlib1g-dev libssl1.0-dev &&     rm -rf /usr/src /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc /usr/share/doc-base /usr/share/man /usr/share/locale /usr/share/zoneinfo /usr/src &&     groupadd -g 1000 -o nginx &&     useradd --shell /usr/sbin/nologin -u 1000 -o -c "" -g 1000 -G www-data nginx' returned a non-zero code: 2

**Comment by pgaertig** [comment]
Fixed in v1.4.1
