### ISSUE TITLE
clean-up files after backend error

### ISSUE THREAD

**Issue by stepin** [pgaertig/nginx-big-upload#9]
Add something like:

syntax: upload_cleanup <HTTP status/range> [<HTTP status/range>...]
default: none
severity: optional
context: server, location
Specifies HTTP statuses after generation of which all file successfuly uploaded in current request will be removed. Used for cleanup after backend or server failure. Backend may also explicitly signal errornous status if it doesn't need uploaded files for some reason. HTTP status must be a numerical value in range 400-599, no leading zeroes are allowed. Ranges of statuses could be specified with a dash.

example: 
upload_cleanup 400 404 499 500-505;

**Comment by pgaertig** [comment]
PRs are welcome. For my use cases currently backend handles further file processing (including deletion). Another solution is to retry upload by client with new session ID. As a clean-up routine I use hourly scheduled cron job to clear temporary files older than one day (modification time):
    9 * * * * /usr/bin/find /storage/tmp-uploads/ -mtime +1 -type f -exec rm -f {} \;
